# Rhythia-reimagined (lite) patcher for Rhythia Legacy (no Python needed) - generated by ssp_mod.py package
# Usage: run "Install.bat" / "Uninstall.bat" from inside the game folder (next to SoundSpacePlus.exe).
param([ValidateSet('install', 'uninstall')][string]$Mode = 'install')
$ErrorActionPreference = 'Stop'

Add-Type -TypeDefinition @'
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

public class GdPck {
    class Ent { public byte[] Raw; public string Path; public long Off; public long Size; public byte[] Md5; public byte[] Data; }
    string fn; byte[] head;
    List<Ent> ents = new List<Ent>();
    Dictionary<string, Ent> by = new Dictionary<string, Ent>();

    public GdPck(string f) {
        fn = f;
        using (var r = new BinaryReader(File.OpenRead(f))) {
            head = r.ReadBytes(84);
            if (Encoding.ASCII.GetString(head, 0, 4) != "GDPC") throw new Exception("not a Godot .pck file");
            uint n = r.ReadUInt32();
            for (uint i = 0; i < n; i++) {
                var e = new Ent();
                int l = (int)r.ReadUInt32();
                e.Raw = r.ReadBytes(l);
                e.Path = Encoding.UTF8.GetString(e.Raw).TrimEnd('\0');
                e.Off = (long)r.ReadUInt64(); e.Size = (long)r.ReadUInt64(); e.Md5 = r.ReadBytes(16);
                ents.Add(e); by[e.Path] = e;
            }
        }
    }
    public int[] Version() { return new int[] { BitConverter.ToInt32(head, 8), BitConverter.ToInt32(head, 12), BitConverter.ToInt32(head, 16) }; }
    public bool Has(string p) { return by.ContainsKey(p); }
    public string Md5(string p) { return BitConverter.ToString(by[p].Md5).Replace("-", "").ToLower(); }
    public string[] Paths() { var a = new List<string>(); foreach (var e in ents) a.Add(e.Path); return a.ToArray(); }

    public byte[] Read(string p) {
        var e = by[p];
        if (e.Data != null) return e.Data;
        using (var fs = File.OpenRead(fn)) return ReadAt(fs, e);
    }
    static byte[] ReadAt(Stream fs, Ent e) {
        fs.Seek(e.Off, SeekOrigin.Begin);
        var b = new byte[e.Size]; int got = 0;
        while (got < b.Length) { int k = fs.Read(b, got, b.Length - got); if (k <= 0) throw new Exception("truncated .pck"); got += k; }
        return b;
    }
    public void Put(string p, byte[] d) {
        Ent e;
        if (!by.TryGetValue(p, out e)) {
            var raw = Encoding.UTF8.GetBytes(p);
            var padded = new byte[raw.Length + (4 - raw.Length % 4) % 4];
            Array.Copy(raw, padded, raw.Length);
            e = new Ent(); e.Raw = padded; e.Path = p; e.Md5 = new byte[16]; e.Off = long.MaxValue;
            ents.Add(e); by[p] = e;
        }
        e.Data = d;
    }
    public void Remove(string p) { Ent e; if (by.TryGetValue(p, out e)) { ents.Remove(e); by.Remove(p); } }

    // rebuild the whole pck compactly (16-byte aligned, index first)
    public void Save() {
        long idx = 88; foreach (var e in ents) idx += 4 + e.Raw.Length + 32;
        long pos = (idx + 15) / 16 * 16;
        var order = new List<Ent>(ents); order.Sort((a, b) => a.Off.CompareTo(b.Off));
        var place = new Dictionary<Ent, long>();
        foreach (var e in order) { place[e] = pos; long size = e.Data != null ? e.Data.Length : e.Size; pos = (pos + size + 15) / 16 * 16; }
        string tmp = fn + ".tmp";
        using (var src = File.OpenRead(fn))
        using (var o = new BinaryWriter(File.Create(tmp))) {
            o.Write(head); o.Write((uint)ents.Count);
            foreach (var e in ents) {
                long size = e.Data != null ? e.Data.Length : e.Size;
                o.Write((uint)e.Raw.Length); o.Write(e.Raw); o.Write((ulong)place[e]); o.Write((ulong)size); o.Write(e.Md5);
            }
            foreach (var e in order) {
                long gap = place[e] - o.BaseStream.Position;
                if (gap > 0) o.Write(new byte[gap]);
                o.Write(e.Data != null ? e.Data : ReadAt(src, e));
            }
        }
        File.Delete(fn); File.Move(tmp, fn);
    }
}
'@

# filled in by ssp_mod.py package:
# game scripts these mods replace (mod/file) -> original script + md5 of the compiled original it was written against
$Swap = [ordered]@{
@@SWAP@@
}
$New = @@NEW@@
$ModDir = 'res://mods/'
$ModDirs = @@MODDIRS@@
$Utf8 = New-Object System.Text.UTF8Encoding($false)
function Remap($path) { $Utf8.GetBytes("[remap]`n`npath=`"$path`"`n") }
function Fail($msg) { Write-Host ""; Write-Host "  $msg" -ForegroundColor Red; Write-Host ""; exit 1 }

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$game = @($here, (Split-Path -Parent $here), (Split-Path -Parent (Split-Path -Parent $here))) | Where-Object { Test-Path (Join-Path $_ 'SoundSpacePlus.pck') } | Select-Object -First 1
if (-not $game) {
    Write-Host "Could not find SoundSpacePlus.pck next to this folder."
    $game = (Read-Host "Paste the Rhythia Legacy game folder path").Trim('"', ' ')
    if (-not (Test-Path (Join-Path $game 'SoundSpacePlus.pck'))) { Fail "No SoundSpacePlus.pck in '$game'." }
}
$pckPath = Join-Path $game 'SoundSpacePlus.pck'
$exe = (Join-Path $game 'SoundSpacePlus.exe').ToLower()
foreach ($proc in @(Get-Process -Name SoundSpacePlus -ErrorAction SilentlyContinue)) {
    if (-not $proc.Path -or $proc.Path.ToLower() -eq $exe) { Fail "Close the game first, then run this again." }
}

Write-Host "Game file: $pckPath"
# switching from the full pack: put its original game file back first
if ($Mode -eq 'install') {
    $full = "$pckPath.tweaks-backup"
    if (Test-Path $full) { Write-Host "Full version found - restoring the original game file first..."; Copy-Item $full $pckPath -Force; Remove-Item $full }
}
$pk = New-Object GdPck $pckPath

# what is installed right now?
foreach ($f in $Swap.Keys) {
    $orig = $Swap[$f][0]; $gdc = $orig.Substring(0, $orig.Length - 3) + '.gdc'
    if (-not $pk.Has($orig + '.remap') -or -not $pk.Has($gdc)) { Fail "This doesn't look like Rhythia Legacy (missing $orig)." }
    if ($pk.Md5($gdc) -ne $Swap[$f][1]) {
        Fail "Your game version is different from the one this mod was made for (Rhythia Legacy nightly, Godot 3.6.2). Nothing was changed."
    }
    $cur = $Utf8.GetString($pk.Read($orig + '.remap'))
    if ($cur -notmatch [regex]::Escape("path=`"$gdc`"") -and $cur -notmatch [regex]::Escape("path=`"$ModDir$f`"")) {
        Fail "$orig is already replaced by another mod ($($cur.Trim() -replace '\s+', ' ')). Nothing was changed."
    }
}

if ($Mode -eq 'install') {
    $files = Join-Path $here 'files'
    foreach ($f in @($Swap.Keys) + $New) { if (-not (Test-Path (Join-Path $files $f))) { Fail "Missing files/$f - extract the whole zip." } }
    $bak = "$pckPath.replaymod-backup"
    if (-not (Test-Path $bak)) { Write-Host "Backing up the original game file -> $(Split-Path -Leaf $bak)"; Copy-Item $pckPath $bak }
    # updating: drop the previous version's files so nothing old is left behind
    foreach ($p in $pk.Paths()) { foreach ($d in $ModDirs) { if ($p.StartsWith($d)) { $pk.Remove($p) } } }
    foreach ($f in $Swap.Keys) {
        $pk.Put($ModDir + $f, [IO.File]::ReadAllBytes((Join-Path $files $f)))
        $pk.Put($Swap[$f][0] + '.remap', (Remap ($ModDir + $f)))
    }
    foreach ($f in $New) { $pk.Put($ModDir + $f, [IO.File]::ReadAllBytes((Join-Path $files $f))) }
    Write-Host "Patching..."
    $pk.Save()
    Write-Host ""
    Write-Host "  Installed! Start the game - there's a new 'Replays' button in the sidebar and star ratings on maps." -ForegroundColor Green
} else {
    foreach ($f in $Swap.Keys) {
        $orig = $Swap[$f][0]
        $pk.Put($orig + '.remap', (Remap ($orig.Substring(0, $orig.Length - 3) + '.gdc')))
    }
    foreach ($p in $pk.Paths()) { foreach ($d in $ModDirs) { if ($p.StartsWith($d)) { $pk.Remove($p) } } }
    Write-Host "Restoring..."
    $pk.Save()
    Write-Host ""
    Write-Host "  Uninstalled - the game is back to normal." -ForegroundColor Green
}
Write-Host ""
